import { FormEvent, useEffect, useState } from 'react';
import { cardsClient, type CreditCard, type Invoice } from '../../app/cards-client';
import { readSession } from '../../app/auth-client';

const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const currentMonth = new Date().toISOString().slice(0,7);

export function CreditCards() {
  const [cards,setCards]=useState<CreditCard[]>([]); const [invoices,setInvoices]=useState<Invoice[]>([]); const [month,setMonth]=useState(currentMonth);
  const [name,setName]=useState(''); const [limit,setLimit]=useState(''); const [closing,setClosing]=useState('5'); const [due,setDue]=useState('12');
  const [selected,setSelected]=useState(''); const [description,setDescription]=useState(''); const [amount,setAmount]=useState(''); const [qty,setQty]=useState('1'); const [error,setError]=useState('');
  const canWrite=readSession()?.user.role!=='VIEWER';
  async function load(){try{setError(''); const [cardData,invoiceData]=await Promise.all([cardsClient.list(),cardsClient.invoices(month)]); setCards(cardData); setInvoices(invoiceData); if(!selected&&cardData[0])setSelected(cardData[0].id);}catch(e){setError(e instanceof Error?e.message:'LOAD_ERROR')}}
  useEffect(()=>{void load()},[month]);
  async function createCard(e:FormEvent){e.preventDefault();try{await cardsClient.create({name,creditLimit:Number(limit),closingDay:Number(closing),dueDay:Number(due),color:'#0f927f'});setName('');setLimit('');await load()}catch(c){setError(c instanceof Error?c.message:'SAVE_ERROR')}}
  async function addPurchase(e:FormEvent){e.preventDefault();try{await cardsClient.addPurchase(selected,{description,totalAmount:Number(amount),installmentQty:Number(qty),purchaseDate:new Date().toISOString().slice(0,10)});setDescription('');setAmount('');setQty('1');await load()}catch(c){setError(c instanceof Error?c.message:'SAVE_ERROR')}}
  return <section className="page cards-page"><header className="page-header"><div><span>Crédito pessoal</span><h1>Cartões e faturas</h1><p>Limites, compras parceladas e previsão mensal em um só lugar.</p></div><label className="month-control">Fatura<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></header>
    {error&&<div className="auth-error">{error==='CARD_LIMIT_EXCEEDED'?'Limite do cartão excedido.':error}</div>}
    <div className="card-grid">{cards.map(card=><article className="credit-card" key={card.id} style={{background:card.color}}><span>{card.issuer||'MEG Card'}</span><h3>{card.name}</h3><p>•••• {card.lastFour||'0000'}</p><div><small>Disponível</small><strong>{money.format(card.availableLimit)}</strong></div><progress value={card.committed} max={Number(card.creditLimit)}/></article>)}{cards.length===0&&<div className="meg-card empty-state">Cadastre seu primeiro cartão.</div>}</div>
    <div className="cards-layout"><form className="meg-card catalog-form" onSubmit={createCard}><span className="meg-eyebrow">Novo cartão</span><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required disabled={!canWrite}/></label><label>Limite<input type="number" step=".01" value={limit} onChange={e=>setLimit(e.target.value)} required disabled={!canWrite}/></label><div className="form-row"><label>Fechamento<input type="number" min="1" max="31" value={closing} onChange={e=>setClosing(e.target.value)}/></label><label>Vencimento<input type="number" min="1" max="31" value={due} onChange={e=>setDue(e.target.value)}/></label></div><button className="auth-submit" disabled={!canWrite}>Salvar cartão</button></form>
    <form className="meg-card catalog-form" onSubmit={addPurchase}><span className="meg-eyebrow">Nova compra</span><label>Cartão<select value={selected} onChange={e=>setSelected(e.target.value)}>{cards.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Descrição<input value={description} onChange={e=>setDescription(e.target.value)} required/></label><div className="form-row"><label>Valor<input type="number" step=".01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Parcelas<input type="number" min="1" max="120" value={qty} onChange={e=>setQty(e.target.value)}/></label></div><button className="auth-submit" disabled={!canWrite||!selected}>Registrar compra</button></form>
    <div className="meg-card invoice-list"><span className="meg-eyebrow">Faturas de {month}</span>{invoices.map(invoice=><article key={invoice.cardId}><div><strong>{invoice.cardName}</strong><span>Vence dia {invoice.dueDay}</span></div><b>{money.format(invoice.total)}</b><ul>{invoice.items.map(i=><li key={`${i.purchaseId}-${i.installment}`}>{i.description} · {i.installment}/{i.quantity}<span>{money.format(i.amount)}</span></li>)}</ul></article>)}</div></div></section>
}
