import {useRef,useState} from 'react';
import {cardsClient,type CardPurchase,type CreditCard} from '../../app/cards-client';
import {Button,Modal} from '../components/SystemUI';
import {amountInput,amountValue,cents,datePt,errorMessage,money,operationId,type SystemData} from '../app/system-domain';

export function EvolutionPurchaseDialog({purchase,card,data,qaMode,onClose,onSaved}:{purchase:CardPurchase;card:CreditCard;data:SystemData;qaMode:boolean;onClose:()=>void;onSaved:()=>void}){
  const [description,setDescription]=useState(purchase.description),[value,setValue]=useState(amountInput(String(cents(purchase.totalAmount)))),[date,setDate]=useState(purchase.purchaseDate.slice(0,10)),[category,setCategory]=useState(purchase.category?.id||''),[installments,setInstallments]=useState(purchase.installments),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deleting,setDeleting]=useState(false),[preview,setPreview]=useState(false);
  const locked=useRef(false),operation=useRef<{body:string;id:string}|null>(null);
  function idFor(body:unknown){const key=JSON.stringify(body);if(operation.current?.body!==key)operation.current={body:key,id:operationId()};return operation.current!.id;}
  async function save(remove=false){if(qaMode||locked.current)return;locked.current=true;setBusy(true);setError('');try{if(remove){await cardsClient.cancelPurchaseProtected(purchase.id,idFor({delete:purchase.id}));}else{const payload={cardId:card.id,categoryId:category||undefined,description:description.trim(),totalAmount:amountValue(value),purchaseDate:date,installments};await cardsClient.updatePurchase(purchase.id,{...payload,operationId:idFor(payload)});}onSaved()}catch(e){setError(errorMessage(e))}finally{locked.current=false;setBusy(false)}}
  return <Modal title="Editar compra do cartão" icon="card" onClose={onClose} busy={busy} wide><form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy} className="meg-dialog-body"><div className="meg-result-card"><small>{card.name} · final {card.lastFour}</small><strong>{money(amountValue(value))}</strong><span>Compra vinculada à fatura. A origem permanece no cartão.</span></div><div className="meg-form-grid"><label className="span-two">Descrição<input required minLength={2} value={description} onChange={e=>setDescription(e.target.value.toUpperCase())}/></label><label>Valor total (R$)<input required inputMode="numeric" value={value} onChange={e=>setValue(amountInput(e.target.value))}/></label><label>Data da compra<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Sem categoria</option>{data.categories.filter(c=>!c.type||c.type==='expense').map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Parcelas (1 a 48)<input type="number" min={1} max={48} required value={installments} onChange={e=>setInstallments(Math.max(1,Math.min(48,Number(e.target.value)||1)))}/></label></div><Button icon="list" onClick={()=>setPreview(v=>!v)}>Visualizar parcelas atuais</Button>{preview&&<div className="meg-payment-items meg-scroll">{purchase.entries.map(entry=><div key={entry.id}><span>Parcela {entry.number}/{purchase.installments}<small>Fatura {entry.statementMonth} · {entry.status==='open'?'Em aberto':'Paga'}{entry.paidAt?' · '+datePt(entry.paidAt):''}</small></span><b>{money(entry.amount)}</b></div>)}<p className="meg-info">Ao salvar, o servidor valida e recalcula o parcelamento. Parcelas pagas permanecem protegidas.</p></div>}{deleting&&<p className="meg-error">Confirme a exclusão da compra e de suas parcelas em aberto.</p>}{error&&<p className="meg-error" role="alert">{error}</p>}{qaMode&&<p className="meg-info">Prévia visual. Operações financeiras desativadas.</p>}</fieldset><footer><Button disabled={busy||qaMode} onClick={()=>deleting?void save(true):setDeleting(true)} icon="x">{deleting?'Confirmar exclusão':'Excluir compra'}</Button><Button disabled={busy} onClick={onClose}>Cancelar</Button><Button primary type="submit" disabled={busy||qaMode||amountValue(value)<=0}>Salvar alterações</Button></footer></form></Modal>;
}
