import {useEffect,useMemo,useRef,useState} from 'react';
import {authenticatedRequest,type AuthSession} from '../../app/auth-client';
import {readCloudState,patchCloudStateProperties} from '../../app/app-state-client';
import {cardsClient,type CreditCard} from '../../app/cards-client';
import {financeClient,type FinancialEvent,type PaymentMethod} from '../../app/finance-client';
import {EvolutionFinancialIcon as Icon,resolveEvolutionFinancialIcon} from '../components/EvolutionFinancialIcon';
import {Button,CategorySummary,Metric,Panel} from '../components/SystemUI';
import {datePt,isBenefit,money,monthPt,normalize,posted,signed,sum,type SystemData} from '../app/system-domain';
import '../styles/evolution-parity.css';

export type EvolutionHomePrefs={balance:boolean;flow:boolean;summary:boolean;benefit:boolean;history:boolean;agenda:boolean};
const PREF_KEY='meg.dashboard.preferences';
const DEFAULT_PREFS:EvolutionHomePrefs={balance:true,flow:true,summary:true,benefit:true,history:true,agenda:true};

export function readEvolutionHomePrefs():EvolutionHomePrefs{
  try{return {...DEFAULT_PREFS,...JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}}catch{return DEFAULT_PREFS}
}
export function applyEvolutionHomePrefs(value:EvolutionHomePrefs){
  try{localStorage.setItem(PREF_KEY,JSON.stringify(value))}catch{}
  const root=document.documentElement;
  Object.entries(value).forEach(([key,enabled])=>root.dataset['megEvolutionHome'+key.slice(0,1).toUpperCase()+key.slice(1)]=enabled?'on':'off');
  window.dispatchEvent(new CustomEvent('meg:evolution-home-prefs',{detail:value}));
}

function downloadBlob(filename:string,blob:Blob){
  const url=URL.createObjectURL(blob),anchor=document.createElement('a');
  anchor.href=url;anchor.download=filename;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);
}
function exportExcel(filename:string,rows:string[][]){
  const esc=(value:string)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const html='<html><head><meta charset="utf-8"></head><body><table border="1">'+rows.map((row,index)=>'<tr>'+row.map(cell=>`<${index===0?'th':'td'}>${esc(cell)}</${index===0?'th':'td'}>`).join('')+'</tr>').join('')+'</table></body></html>';
  downloadBlob(filename,new Blob(['\uFEFF'+html],{type:'application/vnd.ms-excel;charset=utf-8'}));
}
function pdfSafe(value:string){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,' ').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function exportPdf(filename:string,title:string,rows:string[][]){
  const lines=[title,'',...rows.slice(1).map(row=>`${row[1]}  ${row[0]}  ${row[2]?'Parc. '+row[2]+'  ':''}R$ ${row[3]}`)].map(pdfSafe),perPage=48,pages:string[][]=[];
  for(let index=0;index<lines.length;index+=perPage)pages.push(lines.slice(index,index+perPage));if(!pages.length)pages.push([pdfSafe(title)]);
  const objects:string[]=[];const kids:string[]=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  pages.forEach((page,index)=>{const pageObj=4+index*2,contentObj=pageObj+1;kids.push(`${pageObj} 0 R`);const commands=page.map((line,lineIndex)=>`BT /F1 ${lineIndex===0?14:9} Tf 40 ${800-lineIndex*15} Td (${line}) Tj ET`).join('\n');objects[pageObj]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentObj} 0 R >>`;objects[contentObj]=`<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`});
  objects[2]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>`;let pdf='%PDF-1.4\n';const offsets:number[]=[0];
  for(let id=1;id<objects.length;id+=1){offsets[id]=pdf.length;pdf+=`${id} 0 obj\n${objects[id]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let id=1;id<objects.length;id+=1)pdf+=String(offsets[id]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;downloadBlob(filename,new Blob([pdf],{type:'application/pdf'}));
}

type CardTab='summary'|'current'|'upcoming'|'installments'|'history';
type CardRow={id:string;eventId?:string;purchaseId?:string;description:string;date:string;amount:number;installmentNo?:number;installmentQty?:number;statementMonth?:string;category?:string;status?:string};
function purchaseRows(card:CreditCard):CardRow[]{
  return (card.purchases||[]).flatMap(purchase=>(purchase.entries||[]).map(entry=>({id:entry.id,purchaseId:purchase.id,description:purchase.description,date:purchase.purchaseDate,amount:Math.abs(Number(entry.amount||0)),installmentNo:entry.number,installmentQty:purchase.installments,statementMonth:entry.statementMonth,category:purchase.category?.name,status:entry.status})));
}
function statementRows(card:CreditCard):CardRow[]{
  return (card.statement?.lines||[]).map(line=>({id:line.id,eventId:line.eventId||undefined,purchaseId:line.purchaseId||undefined,description:line.description,date:line.purchaseDate,amount:Math.abs(Number(line.effect||0)),installmentNo:line.installmentNo,installmentQty:line.installmentQty,statementMonth:line.statementMonth,status:line.isOpen?'open':'paid'}));
}
export function EvolutionCardCenter({card,month,onPay,onOpenPurchase,onOpenEvent,disabled}:{card:CreditCard;month:string;onPay:()=>void;onOpenPurchase:(purchaseId:string)=>void;onOpenEvent:(eventId:string)=>void;disabled:boolean}){
  const [tab,setTab]=useState<CardTab>('summary'),[query,setQuery]=useState('');
  const all=useMemo(()=>purchaseRows(card),[card]),current=useMemo(()=>statementRows(card),[card]);
  const source=useMemo(()=>{if(tab==='current')return current;if(tab==='upcoming')return all.filter(row=>(row.statementMonth||'')>month);if(tab==='installments')return all.filter(row=>Number(row.installmentQty||1)>1);if(tab==='history')return all;const currentIds=new Set(current.map(row=>row.id));return current.concat(all.filter(row=>!currentIds.has(row.id)&&(row.statementMonth||'')>month)).slice(0,8)},[tab,current,all,month]);
  const filtered=source.filter(row=>!normalize(query)||normalize([row.description,row.category,row.statementMonth].filter(Boolean).join(' ')).includes(normalize(query)));
  const payable=Number(card.statement?.payableAmount??card.payableStatementAmount??Math.max(0,card.statementAmount)),limit=Number(card.creditLimit||0),used=Number(card.usedLimit||0),available=Number(card.availableLimit??Math.max(0,limit-used)),usage=limit?Math.min(100,Math.max(0,used/limit*100)):0,bestDay=Number(card.closingDay||1)>=28?1:Number(card.closingDay||1)+1;
  const rows=[['Descrição','Data','Parcela','Valor'],...filtered.map(row=>[row.description,datePt(row.date),row.installmentNo&&row.installmentQty?`${row.installmentNo}/${row.installmentQty}`:'',row.amount.toFixed(2).replace('.',',')])];
  return <div className="evo-card-center-full">
    <div className="evo-card-center-kpis">
      <Metric label="Limite total" icon="card" value={limit}/><Metric label="Disponível" icon="check-line" tone="green" value={available}/><Metric label="Fatura atual" icon="receipt" tone="yellow" value={payable}/><Metric label="Utilizado" icon="chart" value={used} detail={usage.toFixed(0)+'% do limite'}/>
    </div>
    <Panel title="Central da fatura" icon="card" className="evo-card-ledger" action={<Button primary icon="wallet" disabled={disabled||payable<=0} onClick={onPay}>Pagar fatura</Button>}>
      <div className="evo-card-facts"><span>Fechamento<strong>Dia {card.closingDay||'—'}</strong></span><span>Vencimento<strong>{card.statement?.dueDate?datePt(card.statement.dueDate):'Dia '+(card.dueDay||'—')}</strong></span><span>Melhor dia<strong>Dia {bestDay}</strong></span><span>Competência<strong>{monthPt(month)}</strong></span></div>
      <div className="evo-subtabs">{([['summary','Resumo'],['current','Atual'],['upcoming','Próximas'],['installments','Parcelas'],['history','Histórico']] as Array<[CardTab,string]>).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
      <div className="evo-table-tools"><label><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar lançamentos da fatura"/></label><button title="Exportar Excel" aria-label="Exportar Excel" onClick={()=>exportExcel('fatura-'+normalize(card.name).replace(/\s+/g,'-')+'.xls',rows)}><Icon name="list"/></button><button title="Exportar PDF" aria-label="Exportar PDF" onClick={()=>exportPdf('fatura-'+normalize(card.name).replace(/\s+/g,'-')+'.pdf','Fatura - '+card.name,rows)}><Icon name="note"/></button></div>
      <div className="meg-scroll"><table className="meg-table"><thead><tr><th>Data</th><th>Descrição</th><th>Parcela</th><th>Fatura</th><th>Status</th><th>Valor</th><th/></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td>{datePt(row.date)}</td><td><div className="meg-event-desc"><i className="meg-event-icon"><Icon name={resolveEvolutionFinancialIcon({description:row.description,categoryName:row.category})}/></i><span>{row.description}</span></div></td><td>{row.installmentNo&&row.installmentQty?`${row.installmentNo}/${row.installmentQty}`:'À vista'}</td><td>{row.statementMonth?monthPt(row.statementMonth):monthPt(month)}</td><td><span className={'meg-pill '+(row.status==='paid'?'green':'yellow')}>{row.status==='paid'?'Pago':'Na fatura'}</span></td><td>{money(row.amount)}</td><td>{row.purchaseId||row.eventId?<button className="meg-row-edit" onClick={()=>row.purchaseId?onOpenPurchase(row.purchaseId):row.eventId&&onOpenEvent(row.eventId)}><Icon name="note" size={17}/></button>:null}</td></tr>)}</tbody></table>{!filtered.length?<p className="meg-empty">Nenhum lançamento neste filtro.</p>:null}</div>
    </Panel>
  </div>
}

export function EvolutionHistory({data}:{data:SystemData}){
  const [query,setQuery]=useState(''),items=[...data.audit.items].sort((a,b)=>String(b.at).localeCompare(String(a.at))).filter(item=>!normalize(query)||normalize([item.action,item.entity,item.entityId,item.actor?.name].join(' ')).includes(normalize(query)));
  return <div className="meg-module-grid evo-history"><header className="meg-page-head"><div><h1>Histórico</h1><p>Alterações e confirmações registradas no MEG.</p></div></header><div className="meg-module-metrics"><Metric label="Registros carregados" icon="clock" value={items.length}/><Metric label="Página de auditoria" icon="list" value={data.audit.page}/></div><Panel title="Atividades" icon="clock"><div className="evo-table-tools"><label><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ação, entidade ou usuário"/></label></div><div className="evo-audit-list meg-scroll">{items.map(item=><article key={item.id}><i><Icon name={/settle|paid|payment/i.test(item.action)?'check-line':/delete|archive/i.test(item.action)?'x':'note'}/></i><span><small>{item.at?new Date(item.at).toLocaleString('pt-BR'):'Registro'}</small><strong>{String(item.action||'ATUALIZAÇÃO').replace(/_/g,' ')}</strong><em>{item.entity}{item.entityId?' · '+item.entityId:''}</em></span><b>{item.actor?.name||'Sistema'}</b></article>)}{!items.length?<p className="meg-empty">Nenhuma atividade encontrada.</p>:null}</div></Panel></div>
}

export function EvolutionCashflow({data}:{data:SystemData}){
  const [tab,setTab]=useState<'summary'|'income'|'expense'>('summary'),days=data.cashflow.days||[],visible=days.filter(day=>tab==='summary'||tab==='income'&&Number(day.income)>0||tab==='expense'&&Number(day.expense)>0),result=Number(data.cashflow.totalIncome||0)-Number(data.cashflow.totalExpense||0),max=Math.max(1,...days.flatMap(day=>[Number(day.income||0),Number(day.expense||0)]));
  return <div className="meg-module-grid evo-analysis"><header className="meg-page-head"><div><h1>Fluxo de caixa</h1><p>Entradas, saídas e evolução do saldo no período.</p></div></header><div className="evo-subtabs">{[['summary','Resumo'],['income','Entradas'],['expense','Saídas']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key as typeof tab)}>{label}</button>)}</div><div className="meg-module-metrics"><Metric label="Entradas" icon="up" tone="green" value={data.cashflow.totalIncome}/><Metric label="Saídas" icon="down" tone="red" value={data.cashflow.totalExpense}/><Metric label="Resultado" icon="trend" value={result}/><Metric label="Fechamento realizado" icon="wallet" value={data.cashflow.realizedClosing}/></div><div className="meg-data-with-summary"><Panel title="Evolução diária" icon="chart" className="meg-table-panel"><div className="evo-daily-bars" aria-label="Evolução diária">{days.slice(-31).map(day=><span key={day.date} title={datePt(day.date)}><i className="income" style={{height:Math.max(3,Number(day.income||0)/max*100)+'%'}}/><i className="expense" style={{height:Math.max(3,Number(day.expense||0)/max*100)+'%'}}/></span>)}</div><div className="meg-scroll"><table className="meg-table"><thead><tr><th>Data</th><th>Entradas</th><th>Saídas</th><th>Saldo realizado</th><th>Projetado</th></tr></thead><tbody>{visible.map(day=><tr key={day.date}><td>{datePt(day.date)}</td><td className="green">{money(day.income)}</td><td className="red">{money(day.expense)}</td><td>{money(day.realizedBalance)}</td><td>{money(day.projectedBalance)}</td></tr>)}</tbody></table></div></Panel><Panel title="Posição do período" icon="wallet" className="meg-summary-panel"><div className="meg-result-card"><small>Saldo inicial</small><strong>{money(data.cashflow.openingBalance)}</strong><span>Fechamento projetado {money(data.cashflow.projectedClosing)}</span></div></Panel></div></div>
}

export function EvolutionAnalytics({data}:{data:SystemData}){
  const [tab,setTab]=useState<'overview'|'categories'|'compare'>('overview'),trend=data.analytics.monthlyTrend||[],max=Math.max(1,...trend.flatMap(item=>[Number(item.income||0),Number(item.expense||0)]));
  return <div className="meg-module-grid evo-analysis"><header className="meg-page-head"><div><h1>Relatórios</h1><p>Indicadores para entender hábitos e comparar períodos.</p></div></header><div className="evo-subtabs">{[['overview','Visão geral'],['categories','Categorias'],['compare','Comparar']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key as typeof tab)}>{label}</button>)}</div><div className="meg-module-metrics"><Metric label="Receitas" icon="banknote" tone="green" value={data.analytics.summary.realizedIncome}/><Metric label="Despesas" icon="receipt" tone="red" value={data.analytics.summary.realizedExpense}/><Metric label="Média diária" icon="calendar" value={data.analytics.dailyAverageExpense}/><Metric label="Concentração Top 3" icon="chart" value={data.analytics.concentrationTop3} detail="% das despesas"/></div>{tab!=='compare'?<div className="meg-data-with-summary"><Panel title="Despesas por categoria" icon="chart" className="meg-table-panel"><CategorySummary data={data}/></Panel><Panel title="Leitura do período" icon="note" className="meg-summary-panel"><p>As três maiores categorias concentram <strong>{Number(data.analytics.concentrationTop3||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</strong> das despesas.</p><p>Variação das receitas: <strong>{Number(data.analytics.delta?.income||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</strong>.</p><p>Variação das despesas: <strong>{Number(data.analytics.delta?.expense||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</strong>.</p></Panel></div>:<Panel title="Comparação mensal" icon="chart"><div className="evo-trend-chart">{trend.slice(-12).map(item=><span key={item.month}><b><i className="income" style={{height:Math.max(3,Number(item.income||0)/max*100)+'%'}}/><i className="expense" style={{height:Math.max(3,Number(item.expense||0)/max*100)+'%'}}/></b><small>{item.month.slice(5)}</small></span>)}</div></Panel>}</div>
}

type AvatarPreference={kind:'initials'}|{kind:'preset';presetId:string}|{kind:'photo';dataUrl:string};
const AVATARS=Array.from({length:18},(_,index)=>({id:'people-'+String(index+1).padStart(2,'0'),label:'Avatar '+String(index+1)}));
function avatarKey(userId:string){return 'meg.profile.avatar.'+userId}
function avatarAsset(id:string){const base=(import.meta.env.BASE_URL||'/').replace(/\/?$/,'/');return new URL(base+'brand/avatars/meg-user-base-v2/'+id+'.webp',document.baseURI).href}
function readAvatar(userId:string):AvatarPreference{try{const value=JSON.parse(localStorage.getItem(avatarKey(userId))||'null');if(value?.kind==='photo'&&String(value.dataUrl).startsWith('data:image/'))return value;if(value?.kind==='preset'&&AVATARS.some(item=>item.id===value.presetId))return value;if(value?.kind==='initials')return value}catch{}return {kind:'preset',presetId:'people-01'}}
function avatarImage(value:AvatarPreference){return value.kind==='photo'?value.dataUrl:value.kind==='preset'?avatarAsset(value.presetId):''}
async function saveAvatarCloud(userId:string,value:AvatarPreference){localStorage.setItem(avatarKey(userId),JSON.stringify(value));window.dispatchEvent(new CustomEvent('meg:profile-avatar-changed',{detail:{userId,preference:value}}));for(let attempt=0;attempt<3;attempt+=1){try{const cloud=await readCloudState(),current=(cloud.state.profileAvatars&&typeof cloud.state.profileAvatars==='object'&&!Array.isArray(cloud.state.profileAvatars)?cloud.state.profileAvatars:{}) as Record<string,unknown>;await patchCloudStateProperties({profileAvatars:{...current,[userId]:value}},cloud.revision);return true}catch(error){if((error as {status?:number}).status!==409||attempt===2)return false}}return false}

export function EvolutionSettings({data,session,onChanged}:{data:SystemData;session:AuthSession|null;onChanged:()=>void}){
  const [tab,setTab]=useState<'profile'|'home'|'catalogs'|'security'|'notifications'|'system'>('profile'),[prefs,setPrefs]=useState(readEvolutionHomePrefs),[methods,setMethods]=useState<PaymentMethod[]>(data.allMethods),[cards,setCards]=useState<CreditCard[]>(data.managedCards),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[notifications,setNotifications]=useState<Record<string,unknown>|null>(null),[avatar,setAvatar]=useState<AvatarPreference>(()=>readAvatar(session?.user.id||'preview')),[syncStatus,setSyncStatus]=useState<{token:string;changedAt:string|null;mutationType:string|null}|null>(null);const fileRef=useRef<HTMLInputElement>(null),userId=session?.user.id||'preview';
  useEffect(()=>{applyEvolutionHomePrefs(prefs)},[prefs]);
  useEffect(()=>{setMethods(data.allMethods);setCards(data.managedCards)},[data.allMethods,data.managedCards]);
  useEffect(()=>{if(tab==='notifications'&&session)void authenticatedRequest<Record<string,unknown>>('/notifications/status',{cache:'no-store'}).then(setNotifications).catch(()=>setNotifications(null));if(tab==='system'&&session)void financeClient.getSyncStatus().then(setSyncStatus).catch(()=>setSyncStatus(null))},[tab,session]);
  async function toggleMethod(method:PaymentMethod){if(!session||busy)return;setBusy('method:'+method.id);setMessage('');try{const operationId=crypto.randomUUID(),updated=method.isActive?await financeClient.deactivatePaymentMethod(method.id,{operationId,expectedUpdatedAt:method.updatedAt}):await financeClient.updatePaymentMethod(method.id,{isActive:true,operationId,expectedUpdatedAt:method.updatedAt});setMethods(items=>items.map(item=>item.id===method.id?{...item,...updated}:item));setMessage(method.name+': '+(updated.isActive?'ativado':'desativado')+'.');onChanged()}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível alterar a forma de pagamento.')}finally{setBusy('')}}
  async function toggleCard(card:CreditCard){if(!session||busy)return;setBusy('card:'+card.id);setMessage('');try{const meta={operationId:crypto.randomUUID(),expectedUpdatedAt:card.updatedAt},updated=card.isActive?await cardsClient.deactivate(card.id,meta):(await cardsClient.reactivate(card.id,meta)).card;setCards(items=>items.map(item=>item.id===card.id?{...item,...updated}:item));setMessage(card.name+': '+(updated.isActive?'ativado':'desativado')+'.');onChanged()}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível alterar o cartão.')}finally{setBusy('')}}
  async function testNotifications(){if(!session||busy)return;setBusy('notifications');setMessage('');try{const result=await authenticatedRequest<Record<string,{status?:string}>>('/notifications/test-channels',{method:'POST'}),ok=Object.values(result||{}).filter(item=>item?.status==='sent'||item?.status==='ok').length;setMessage(ok?`Teste enviado para ${ok} canal(is).`:'Teste concluído. Verifique o diagnóstico dos canais.');setNotifications(await authenticatedRequest<Record<string,unknown>>('/notifications/status',{cache:'no-store'}))}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível testar os canais.')}finally{setBusy('')}}
  async function chooseAvatar(next:AvatarPreference){setAvatar(next);setMessage(session?await saveAvatarCloud(userId,next)?'Avatar sincronizado.':'Avatar aplicado localmente. A nuvem será tentada novamente depois.':'Prévia visual: avatar não foi gravado.')}
  async function choosePhoto(file?:File){if(!file)return;if(file.size>450000){setMessage('A foto precisa ter até 450 KB.');return}const reader=new FileReader();reader.onload=()=>{const value=String(reader.result||'');if(value.startsWith('data:image/'))void chooseAvatar({kind:'photo',dataUrl:value})};reader.readAsDataURL(file)}
  const image=avatarImage(avatar);
  return <div className="meg-module-grid evo-settings"><header className="meg-page-head"><div><h1>Configurações</h1><p>Perfil, experiência, meios, avisos e sistema.</p></div></header><nav className="evo-settings-tabs">{([['profile','Perfil'],['home','Home'],['catalogs','Meios'],['security','Segurança'],['notifications','Avisos'],['system','Sistema']] as Array<[typeof tab,string]>).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setMessage('')}}>{label}</button>)}</nav><div className="evo-settings-body meg-scroll">
    {tab==='profile'?<div className="evo-settings-columns"><Panel title="Meu perfil" icon="settings"><div className="evo-profile"><span className={image?'has-image':''}>{image?<img src={image} alt=""/>:(session?.user.name||'M').slice(0,1).toUpperCase()}</span><div><strong>{session?.user.name||'Prévia visual'}</strong><small>{session?.user.email||'Dados ilustrativos'}</small><em>{session?.user.role||'preview'}</em></div></div><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{void choosePhoto(e.target.files?.[0]);e.currentTarget.value=''}}/><div className="evo-profile-actions"><Button disabled={!session} onClick={()=>fileRef.current?.click()}>Escolher foto</Button><Button disabled={!session} onClick={()=>void chooseAvatar({kind:'initials'})}>Usar iniciais</Button></div></Panel><Panel title="Avatares MEG" icon="settings"><div className="evo-avatar-grid">{AVATARS.map(item=><button disabled={!session} key={item.id} className={avatar.kind==='preset'&&avatar.presetId===item.id?'active':''} onClick={()=>void chooseAvatar({kind:'preset',presetId:item.id})}><img src={avatarAsset(item.id)} alt=""/><small>{item.label}</small></button>)}</div></Panel></div>:null}
    {tab==='home'?<Panel title="Monte sua Home" icon="home"><p>Os blocos continuam no layout validado; você escolhe quais ficam visíveis.</p><div className="evo-switch-list">{([['balance','Saldo monetário'],['flow','Fluxo do mês'],['summary','Resumo financeiro'],['benefit','Benefício Alimentação'],['history','Histórico recente'],['agenda','Agenda financeira']] as Array<[keyof EvolutionHomePrefs,string]>).map(([key,label])=><button key={key} className={prefs[key]?'on':''} onClick={()=>setPrefs(current=>({...current,[key]:!current[key]}))}><span><strong>{label}</strong><small>{prefs[key]?'Visível':'Oculto'}</small></span><i><b/></i></button>)}</div><Button onClick={()=>setPrefs(DEFAULT_PREFS)}>Restaurar padrão</Button></Panel>:null}
    {tab==='catalogs'?<div className="evo-settings-columns"><Panel title="Formas de pagamento" icon="wallet"><div className="evo-manage-list">{methods.map(method=><button disabled={!session||Boolean(busy)} key={method.id} onClick={()=>void toggleMethod(method)}><span><strong>{method.name}</strong><small>{method.type||'Forma de pagamento'}</small></span><i className={method.isActive?'on':''}><b/></i></button>)}</div></Panel><Panel title="Cartões disponíveis" icon="card"><div className="evo-manage-list">{cards.map(card=><button disabled={!session||Boolean(busy)} key={card.id} onClick={()=>void toggleCard(card)}><span><strong>{card.name}</strong><small>{card.lastFour?'Final '+card.lastFour:'Cartão cadastrado'} · {card.isActive?'Ativo':'Inativo'}</small></span><i className={card.isActive?'on':''}><b/></i></button>)}</div></Panel></div>:null}
    {tab==='security'?<Panel title="Segurança" icon="alert"><div className="evo-native-boundary"><Icon name="alert"/><span><strong>Sessão Web protegida</strong><small>A biometria permanece exclusiva do aplicativo Android porque depende do sensor e do armazenamento seguro do aparelho. A Web não simula esse recurso.</small></span></div><div className="evo-native-boundary"><Icon name="phone"/><span><strong>Biometria Android preservada</strong><small>O código nativo continua intacto e disponível no APK.</small></span></div></Panel>:null}
    {tab==='notifications'?<Panel title="Canais de aviso" icon="bell"><p>Diagnóstico dos lembretes e integrações remotas compartilhadas pelo MEG.</p><Button primary disabled={!session||Boolean(busy)} onClick={()=>void testNotifications()}>{busy==='notifications'?'Testando…':'Testar canais'}</Button><pre className="evo-status-json">{notifications?JSON.stringify(notifications,null,2):'Status indisponível ou ainda carregando.'}</pre><div className="evo-native-boundary"><Icon name="phone"/><span><strong>Notificação local Android</strong><small>Permanece no APK. A Web usa apenas os canais remotos suportados pelo backend.</small></span></div></Panel>:null}
    {tab==='system'?<Panel title="Sistema e sincronização" icon="settings"><div className="evo-system-status"><span><small>Estado da nuvem</small><strong>{syncStatus?'Sincronizado':'Indisponível'}</strong></span><span><small>Última alteração</small><strong>{syncStatus?.changedAt?new Date(syncStatus.changedAt).toLocaleString('pt-BR'):'—'}</strong></span><span><small>Tipo</small><strong>{syncStatus?.mutationType||'—'}</strong></span></div><div className="evo-native-boundary"><Icon name="repeat"/><span><strong>Atualização OTA do APK</strong><small>Permanece exclusiva do Android. No navegador, a versão publicada é carregada pelo deploy Web.</small></span></div></Panel>:null}
    {message?<p className="evo-settings-message">{message}</p>:null}
  </div></div>
}

export function EvolutionBenefitLedger({data,onEdit}:{data:SystemData;onEdit:(event:FinancialEvent)=>void}){
  const [tab,setTab]=useState<'all'|'credits'|'debits'>('all'),[query,setQuery]=useState(''),rows=data.events.filter(isBenefit).filter(event=>posted(event.status)).filter(event=>tab==='all'||tab==='credits'&&signed(event)>0||tab==='debits'&&signed(event)<0).filter(event=>!normalize(query)||normalize([event.description,event.category?.name].join(' ')).includes(normalize(query))).sort((a,b)=>b.date.localeCompare(a.date));
  return <Panel title="Histórico do benefício" icon="list" className="meg-table-panel"><div className="evo-subtabs benefit">{[['all','Todas'],['credits','Entradas'],['debits','Saídas']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key as typeof tab)}>{label}</button>)}</div><div className="evo-table-tools"><label><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar no extrato do benefício"/></label></div><div className="meg-scroll"><table className="meg-table"><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Tipo</th><th>Valor</th><th/></tr></thead><tbody>{rows.map(event=><tr key={event.id}><td>{datePt(event.date)}</td><td>{event.description}</td><td>{event.category?.name||'Benefício'}</td><td><span className={'meg-pill '+(signed(event)>0?'green':'yellow')}>{signed(event)>0?'Recarga':'Consumo'}</span></td><td className={signed(event)>0?'green':'yellow'}>{signed(event)>0?'+ ':'− '}{money(Math.abs(signed(event)))}</td><td><button className="meg-row-edit" onClick={()=>onEdit(event)}><Icon name="note" size={17}/></button></td></tr>)}</tbody></table>{!rows.length?<p className="meg-empty">Nenhuma movimentação neste filtro.</p>:null}</div></Panel>
}

export function EvolutionPeriodOverview({data,events,label,openingBalance,closingBalance,onMovements}:{data:SystemData;events:FinancialEvent[];label:string;openingBalance?:number;closingBalance?:number;onMovements:()=>void}){
  const realized=events.filter(event=>posted(event.status)&&event.type!=='transfer'),income=sum(realized.filter(event=>signed(event)>0&&!isBenefit(event)).map(event=>signed(event))),expense=sum(realized.filter(event=>signed(event)<0&&!isBenefit(event)).map(event=>Math.abs(signed(event)))),result=income-expense,months=new Set(events.map(event=>String(event.competence||event.date).slice(0,7)).filter(Boolean));
  return <div className="meg-module-grid evo-period-overview"><header className="meg-page-head"><div><h1>{label}</h1><p>Visão consolidada do período selecionado.</p></div><Button primary icon="list" onClick={onMovements}>Ver lançamentos</Button></header><div className="meg-module-metrics">{openingBalance!==undefined?<Metric label="Saldo inicial" icon="wallet" value={openingBalance}/>:<Metric label="Meses com movimentos" icon="calendar" value={months.size}/>}<Metric label="Receitas realizadas" icon="up" tone="green" value={income}/><Metric label="Despesas realizadas" icon="down" tone="red" value={expense}/><Metric label="Resultado consolidado" icon="trend" value={result}/></div>{closingBalance!==undefined?<Panel title="Fechamento do intervalo" icon="wallet"><div className="meg-result-card"><small>Saldo ao fim do período</small><strong>{money(closingBalance)}</strong><span>Saldo atual de benefício {money(data.benefit.balance)}</span></div></Panel>:<Panel title="Posição atual" icon="wallet"><div className="meg-result-card"><small>Saldo monetário atual</small><strong>{money(Number(data.summary.availableBalance||0)+Number(data.summary.realizedResult||0))}</strong><span>Benefício atual {money(data.benefit.balance)}</span></div></Panel>}</div>
}
