import { FormEvent, useEffect, useMemo, useState } from 'react';
import { MEGMetric } from '@ui';
import { readSession } from '../../app/auth-client';
import { financeClient, type Account, type Category, type PaymentMethod } from '../../app/finance-client';
import { payablesClient, type Payable } from '../../app/payables-client';
import { useAppStore } from '../../app/store';
import { invalidateFinanceSummary } from '../../app/use-finance-summary';

const brl = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });

export function Payables() {
  const selectedMonth = useAppStore((state) => state.selectedMonth);
  const setSelectedMonth = useAppStore((state) => state.setSelectedMonth);
  const [items, setItems] = useState<Payable[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [methods, setMethods] = useState<PaymentMethod[]>([]);
  const [description, setDescription] = useState(''); const [amount, setAmount] = useState('');
  const [dueDate, setDueDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [installmentQty, setInstallmentQty] = useState('1'); const [categoryId, setCategoryId] = useState('');
  const [recurring, setRecurring] = useState(false); const [frequency, setFrequency] = useState<'weekly' | 'monthly' | 'yearly'>('monthly'); const [endDate, setEndDate] = useState('');
  const [paying, setPaying] = useState<Payable | null>(null); const [paymentAmount, setPaymentAmount] = useState(''); const [accountId, setAccountId] = useState(''); const [paymentMethodId, setPaymentMethodId] = useState('');
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const role = readSession()?.user.role || 'VIEWER'; const canWrite = role !== 'VIEWER'; const canCancel = role === 'ADMIN' || role === 'MANAGER';

  async function load() { setLoading(true); setError(''); try { const [payableData, categoryData, accountData, methodData] = await Promise.all([payablesClient.list(selectedMonth), financeClient.listCategories(), financeClient.listAccounts(), financeClient.listPaymentMethods()]); setItems(payableData); setCategories(categoryData.filter((item) => item.isActive && item.type !== 'income')); setAccounts(accountData.filter((item) => item.isActive)); setMethods(methodData.filter((item) => item.isActive)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'PAYABLES_LOAD_ERROR'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [selectedMonth]);

  const totals = useMemo(() => { const now = new Date(); return { open: items.filter((item) => item.status !== 'paid').reduce((sum, item) => sum + Number(item.openAmount), 0), overdue: items.filter((item) => item.status !== 'paid' && new Date(item.dueDate) < now).reduce((sum, item) => sum + Number(item.openAmount), 0), paid: items.filter((item) => item.status === 'paid').reduce((sum, item) => sum + Number(item.totalAmount), 0), count: items.filter((item) => item.status !== 'paid').length }; }, [items]);

  async function submit(event: FormEvent) { event.preventDefault(); const value = Number(amount.replace(',', '.')); if (!canWrite || !description.trim() || value <= 0) return; setBusy(true); try { if (recurring) await payablesClient.createRecurring({ description: description.trim(), amount: value, categoryId: categoryId || undefined, frequency, nextDueDate: dueDate, endDate: endDate || undefined }); else await payablesClient.create({ description: description.trim(), totalAmount: value, categoryId: categoryId || undefined, dueDate, installmentQty: Number(installmentQty) }); setDescription(''); setAmount(''); setInstallmentQty('1'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'PAYABLE_SAVE_ERROR'); } finally { setBusy(false); } }
  async function confirmPayment(event: FormEvent) { event.preventDefault(); if (!paying) return; const value = Number(paymentAmount.replace(',', '.')); if (value <= 0) return; setBusy(true); try { await payablesClient.pay(paying.id, { amount: value, paidAt: new Date().toISOString().slice(0, 10), accountId: accountId || undefined, paymentMethodId: paymentMethodId || undefined }); setPaying(null); setPaymentAmount(''); invalidateFinanceSummary(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'PAYMENT_ERROR'); } finally { setBusy(false); } }

  return <section className="page">
    <header className="page-header compact"><div><span>Contas a pagar</span><h1>Obrigações e recorrências</h1><p>Controle vencimentos, parcelas e pagamentos integrados ao fluxo de caixa.</p></div><label className="catalog-role">Mês<input type="month" value={selectedMonth} onChange={(e) => setSelectedMonth(e.target.value)} /></label></header>
    {error && <div className="auth-error">{error}</div>}
    <section className="metric-grid"><MEGMetric label="Em aberto" value={brl.format(totals.open)} hint={`${totals.count} obrigação(ões)`} tone="warning"/><MEGMetric label="Vencido" value={brl.format(totals.overdue)} hint="Exige atenção" tone={totals.overdue > 0 ? 'danger' : 'good'}/><MEGMetric label="Pago no mês" value={brl.format(totals.paid)} hint="Obrigações quitadas" tone="good"/><MEGMetric label="Comprometimento" value={brl.format(totals.open + totals.paid)} hint={selectedMonth}/></section>
    <div className="catalog-layout"><form className="meg-card catalog-form" onSubmit={submit}><span className="meg-eyebrow">Nova obrigação</span><h3>{recurring ? 'Despesa recorrente' : 'Conta a pagar'}</h3><label className="toggle-row"><input type="checkbox" checked={recurring} onChange={(e) => setRecurring(e.target.checked)} disabled={!canWrite}/> Repetir automaticamente</label><label>Descrição<input value={description} onChange={(e) => setDescription(e.target.value)} disabled={!canWrite} required/></label><label>Valor {recurring ? 'por ocorrência' : 'total'}<input value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="decimal" disabled={!canWrite} required/></label><label>Primeiro vencimento<input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} disabled={!canWrite}/></label>{recurring ? <><label>Frequência<select value={frequency} onChange={(e) => setFrequency(e.target.value as typeof frequency)} disabled={!canWrite}><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label><label>Encerrar em (opcional)<input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} disabled={!canWrite}/></label></> : <label>Parcelas<input type="number" min="1" max="60" value={installmentQty} onChange={(e) => setInstallmentQty(e.target.value)} disabled={!canWrite}/></label>}<label>Categoria<select value={categoryId} onChange={(e) => setCategoryId(e.target.value)} disabled={!canWrite}><option value="">Sem categoria</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.group ? `${item.group} — ` : ''}{item.name}</option>)}</select></label><button className="auth-submit" disabled={!canWrite || busy}>{busy ? 'Salvando...' : 'Salvar obrigação'}</button></form>
      <div className="meg-card catalog-list"><div className="catalog-list-heading"><div><span className="meg-eyebrow">Agenda mensal</span><h3>{items.length} conta(s)</h3></div><button onClick={() => void load()}>Atualizar</button></div><div className="catalog-table">{loading && <p className="catalog-empty">Carregando contas...</p>}{items.map((item) => { const overdue = item.status !== 'paid' && new Date(item.dueDate) < new Date(); return <article key={item.id}><div><strong>{item.description}</strong><span>{item.category?.name || 'Sem categoria'} • vence {new Date(item.dueDate).toLocaleDateString('pt-BR')}{item.installmentQty > 1 ? ` • ${item.installmentNo}/${item.installmentQty}` : ''}</span></div><strong>{brl.format(Number(item.openAmount))}</strong><span className={`status-pill ${item.status === 'paid' ? 'active' : ''}`}>{item.status === 'paid' ? 'Pago' : overdue ? 'Vencido' : item.status === 'partial' ? 'Parcial' : 'Em aberto'}</span><div className="table-actions">{item.status !== 'paid' && canWrite && <button onClick={() => { setPaying(item); setPaymentAmount(String(item.openAmount)); }}>Pagar</button>}{item.status !== 'paid' && canCancel && <button className="danger" onClick={() => void payablesClient.cancel(item.id).then(load)}>Cancelar</button>}</div></article>; })}{!loading && !items.length && <p className="catalog-empty">Nenhuma conta no mês.</p>}</div></div></div>
    {paying && <div className="modal-backdrop"><form className="modal-card" onSubmit={confirmPayment}><header><div><span>Baixa de pagamento</span><h2>{paying.description}</h2></div><button type="button" className="icon-button" onClick={() => setPaying(null)}>×</button></header><div className="form-grid"><label>Valor<input value={paymentAmount} onChange={(e) => setPaymentAmount(e.target.value)} inputMode="decimal"/></label><label>Conta<select value={accountId} onChange={(e) => setAccountId(e.target.value)}><option value="">Não informada</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Forma de pagamento<select value={paymentMethodId} onChange={(e) => setPaymentMethodId(e.target.value)}><option value="">Não informada</option>{methods.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><footer><button type="button" onClick={() => setPaying(null)}>Cancelar</button><button className="auth-submit" disabled={busy}>Confirmar pagamento</button></footer></form></div>}
  </section>;
}