import {useEffect,useId,useRef,type ReactNode} from 'react';
import {EvolutionFinancialIcon as Icon,type EvolutionFinancialIconName as IconName,resolveEvolutionFinancialIcon} from './EvolutionFinancialIcon';
import {datePt,isBenefit,money,posted,signed,sum,type SystemData} from '../app/system-domain';
import type {FinancialEvent} from '../../app/finance-client';

export function Button({children,onClick,icon,primary=false,disabled=false,type='button'}:{children:ReactNode;onClick?:()=>void;icon?:IconName;primary?:boolean;disabled?:boolean;type?:'button'|'submit'}){return <button type={type} className={'meg-control '+(primary?'primary':'')} disabled={disabled} onClick={onClick}>{icon&&<Icon name={icon}/>}<span>{children}</span></button>}
export function Panel({title,icon,action,children,className=''}:{title?:string;icon?:IconName;action?:ReactNode;children:ReactNode;className?:string}){return <section className={'meg-panel '+className}>{title&&<header><h2>{icon&&<Icon name={icon}/>}<span>{title}</span></h2>{action}</header>}{children}</section>}
export function Metric({label,value,icon,tone='',detail,onClick}:{label:string;value:number;icon:IconName;tone?:string;detail?:string;onClick?:()=>void}){const content=<><i className={'meg-icon '+tone}><Icon name={icon}/></i><span><small>{label}</small><strong>{money(value)}</strong>{detail&&<em>{detail}</em>}</span>{onClick&&<Icon name="chevron-right"/>}</>;return onClick?<button className={'meg-metric meg-panel '+tone} onClick={onClick}>{content}</button>:<article className={'meg-metric meg-panel '+tone}>{content}</article>}
export function Modal({title,icon,children,onClose,busy=false,wide=false}:{title:string;icon:IconName;children:ReactNode;onClose:()=>void;busy?:boolean;wide?:boolean}){
  const ref=useRef<HTMLDivElement>(null),titleId=useId();
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const box=ref.current;const focusable=()=>Array.from(box?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')||[]);(focusable()[0]||box)?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const list=focusable();if(!list.length){e.preventDefault();return}const first=list[0],last=list[list.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===box)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus()};},[onClose,busy]);
  return <div className="meg-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><div ref={ref} tabIndex={-1} className={'meg-dialog '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-labelledby={titleId}><header><i className="meg-icon"><Icon name={icon}/></i><div><small>MEG FINANÇAS</small><h2 id={titleId}>{title}</h2></div><button aria-label="Fechar" disabled={busy} onClick={onClose}><Icon name="x"/></button></header>{children}</div></div>;
}
export function EventGlyph({event}:{event:FinancialEvent}){return <i className={'meg-event-icon '+(isBenefit(event)?'yellow':signed(event)>0?'green':'')}><Icon name={signed(event)>0?'banknote':resolveEvolutionFinancialIcon({type:event.type,signedAmount:signed(event),description:event.description,categoryName:event.category?.name,paymentName:event.paymentMethod?.name})}/></i>}
export function EventsTable({events,onEdit,compact=false}:{events:FinancialEvent[];onEdit?:(e:FinancialEvent)=>void;compact?:boolean}){return <div className="meg-scroll" data-meg-scroll-region="true"><table className={'meg-table '+(compact?'compact':'')}><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th>{!compact&&<><th>Conta</th><th>Forma</th><th>Status</th></>}<th>Valor</th>{onEdit&&<th><span className="sr-only">Ações</span></th>}</tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{datePt(e.date)}</td><td><div className="meg-event-desc"><EventGlyph event={e}/><span>{e.description}</span></div></td><td><span className="meg-pill category">{e.category?.name||e.sourceDetails?.group||'Sem categoria'}</span></td>{!compact&&<><td>{e.account?.name||'Na baixa'}</td><td><span className="meg-pill payment">{e.paymentMethod?.name||e.sourceDetails?.paymentMethod||'Na baixa'}</span></td><td><span className={'meg-pill '+(posted(e.status)?'green':'yellow')}>{posted(e.status)?'Pago':'Pendente'}</span></td></>}<td className={isBenefit(e)?'yellow':signed(e)>=0?'green':'red'}>{signed(e)>0?'+ ':signed(e)<0?'− ':''}{money(Math.abs(signed(e)))}</td>{onEdit&&<td><button className="meg-row-edit" onClick={()=>onEdit(e)} aria-label={'Editar '+e.description}><Icon name="note" size={17}/></button></td>}</tr>)}</tbody></table>{!events.length&&<p className="meg-empty">Nenhum lançamento neste período.</p>}</div>}
export function CashChart({data}:{data:SystemData}){const days=data.cashflow.days,max=Math.max(1,...days.flatMap(d=>[Math.abs(d.income),Math.abs(d.expense)]));return <div className="meg-cash-chart" role="img" aria-label={'Entradas '+money(data.cashflow.totalIncome)+', saídas '+money(data.cashflow.totalExpense)}><div className="meg-chart-lines"><i/><i/><i/><i/></div><div className="meg-chart-bars">{days.map((day,i)=><div key={day.date} title={datePt(day.date)+' · Entradas '+money(day.income)+' · Saídas '+money(day.expense)}><span className="positive" style={{height:Math.abs(day.income)/max*45+'%'}}/><span className="negative" style={{height:Math.abs(day.expense)/max*45+'%'}}/>{(i%5===0||i===days.length-1)&&<small>{day.date.slice(8,10)}</small>}</div>)}</div></div>}
export function CategorySummary({data}:{data:SystemData}){const items=data.analytics.categories,total=sum(items.map(i=>Math.abs(i.amount))),colors=['#20e7d2','#ffcb51','#a278ff','#4da8ed','#ff637b','#9ee2cf'];let end=0;const gradient=items.map((item,i)=>{const start=end;end+=total?Math.abs(item.amount)/total*100:0;return `${colors[i%colors.length]} ${start}% ${end}%`}).join(',');return <><div className="meg-donut" style={{background:gradient?'conic-gradient('+gradient+')':'#164344'}}><span><small>Despesas</small><strong>{money(total)}</strong></span></div><div className="meg-category-list">{items.map((item,i)=><div key={item.name}><i style={{background:colors[i%colors.length]}}/><span>{item.name}</span><b>{money(item.amount)}</b></div>)}</div></>}
