import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { MEGCurrencyInput } from '@ui';
import { formatBRLValue, parseBRL } from '@shared/money';
import { readSession } from '../../app/auth-client';
import { financeClient, type Account, type Category, type PaymentMethod } from '../../app/finance-client';
import { cardsClient, type CreditCard } from '../../app/cards-client';

type Tab = 'accounts' | 'classifications' | 'groups' | 'payments' | 'cards';
type Filters = { first: string; second: string; third: string; status: string };
const emptyFilters: Filters = { first: '', second: '', third: '', status: '' };
const brands = ['Visa', 'Mastercard', 'Elo', 'American Express', 'Outra'];

export function FinancialCatalogs() {
  const [tab, setTab] = useState<Tab>('classifications');
  const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [payments, setPayments] = useState<PaymentMethod[]>([]); const [cards, setCards] = useState<CreditCard[]>([]);
  const [filters, setFilters] = useState<Filters>(emptyFilters);
  const [name, setName] = useState(''); const [detail, setDetail] = useState(''); const [type, setType] = useState('expense'); const [extra, setExtra] = useState('');
  const [openingBalance, setOpeningBalance] = useState(() => formatBRLValue(0)); const [closingDay, setClosingDay] = useState('10'); const [dueDay, setDueDay] = useState('17'); const [limit, setLimit] = useState('');
  const [cardFormOpen, setCardFormOpen] = useState(false); const [simulationDate, setSimulationDate] = useState(() => new Date().toLocaleDateString('en-CA', { timeZone: 'America/Sao_Paulo' }));
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const firstField = useRef<HTMLInputElement>(null);
  const role = readSession()?.user.role ?? 'VIEWER'; const canWrite = role !== 'VIEWER'; const canDeactivate = role === 'ADMIN' || role === 'MANAGER';

  async function load() { setLoading(true); setError(''); try { const [a,c,p,cardData] = await Promise.all([financeClient.listAccounts(), financeClient.listCategories(), financeClient.listPaymentMethods(), cardsClient.list(new Date().toISOString().slice(0,7))]); setAccounts(a); setCategories(c); setPayments(p); setCards(cardData); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar os cadastros.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function selectTab(next: Tab) { setTab(next); setFilters(emptyFilters); setName(''); setDetail(''); setExtra(''); setLimit(''); setCardFormOpen(next !== 'cards'); setType(next === 'accounts' ? 'checking' : next === 'payments' ? 'instant' : 'expense'); if (next !== 'cards') window.setTimeout(() => firstField.current?.focus(), 0); }
  const classifications = useMemo(() => [...new Set(categories.filter((item) => item.type !== 'income').map((item) => item.name))].sort(), [categories]);
  const rows = useMemo(() => {
    const source: Array<{id:string;first:string;second:string;third:string;active:boolean}> = tab === 'accounts' ? accounts.map(x=>({id:x.id,first:x.name,second:x.institution||'Monetária',third:x.type,active:x.isActive})) : tab === 'classifications' ? classifications.map(value=>{const related=categories.filter(x=>x.name===value&&x.type!=='income');return{id:related[0]?.id||value,first:value,second:'Somente despesas',third:`${new Set(related.map(x=>x.group).filter(Boolean)).size} grupos`,active:related.some(x=>x.isActive)}}) : tab === 'groups' ? categories.map(x=>({id:x.id,first:x.group||x.name,second:x.type==='income'?'Recebimento':'Despesa',third:x.type==='income'?'Não se aplica':x.name,active:x.isActive})) : tab === 'payments' ? payments.map(x=>({id:x.id,first:x.name,second:x.type||'Outro',third:/credit/i.test(x.type||x.name)?'Cartão cadastrado':'Conta compatível',active:x.isActive})) : cards.map(x=>({id:x.id,first:x.name,second:`${x.issuer||'Emissor não informado'} · ${x.brand||'Bandeira não informada'}`,third:`Fecha dia ${x.closingDay} · vence dia ${x.dueDay}`,active:x.isActive}));
    const match=(value:string,filter:string)=>value.toLowerCase().includes(filter.trim().toLowerCase()); return source.filter(x=>match(x.first,filters.first)&&match(x.second,filters.second)&&match(x.third,filters.third)&&(!filters.status||(filters.status==='active')===x.active));
  }, [tab,accounts,categories,payments,cards,classifications,filters]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!canWrite || !name.trim()) { firstField.current?.focus(); return; } setBusy(true); setError(''); try { if(tab==='accounts') await financeClient.createAccount({name:name.trim(),type,institution:detail||null,openingBalance:parseBRL(openingBalance)||0}); if(tab==='classifications') await financeClient.createCategory({name:name.trim(),group:null,type:'expense'}); if(tab==='groups') await financeClient.createCategory({name:type==='income'?name.trim():detail,group:name.trim(),type:type as 'income'|'expense'}); if(tab==='payments') await financeClient.createPaymentMethod({name:name.trim(),type}); if(tab==='cards') await cardsClient.create({name:name.trim(),issuer:detail||undefined,brand:extra||undefined,creditLimit:parseBRL(limit)||0,closingDay:Number(closingDay),dueDay:Number(dueDay)}); setName('');setDetail('');setExtra('');setLimit('');await load();firstField.current?.focus(); } catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível salvar o cadastro.');} finally{setBusy(false);} }
  async function deactivate(id:string){if(!canDeactivate)return;setBusy(true);try{if(tab==='accounts')await financeClient.deactivateAccount(id);if(tab==='classifications'||tab==='groups')await financeClient.deactivateCategory(id);if(tab==='payments')await financeClient.deactivatePaymentMethod(id);if(tab==='cards')await cardsClient.deactivate(id);await load();}finally{setBusy(false);}}
  const copy=tab==='accounts'?['Conta financeira','Contas financeiras','Nome','Escopo','Tipo']:tab==='classifications'?['Classificação de despesa','Classificações de despesas','Classificação','Uso','Grupos vinculados']:tab==='groups'?['Grupo','Grupos cadastrados','Grupo','Tipo','Classificação']:tab==='payments'?['Forma de pagamento','Formas de pagamento','Nome','Natureza','Compatibilidade']:['Cartão de crédito','Cartões cadastrados','Cartão','Emissor','Regras'];
  const cardDates = useMemo(() => {
    const close = Math.min(31, Math.max(1, Number(closingDay) || 1)); const due = Math.min(31, Math.max(1, Number(dueDay) || 1)); const purchase = new Date(`${simulationDate}T12:00:00`);
    const safe = (year:number,month:number,day:number) => new Date(year,month,Math.min(day,new Date(year,month+1,0).getDate()),12);
    const closing = purchase.getDate() <= close ? safe(purchase.getFullYear(),purchase.getMonth(),close) : safe(purchase.getFullYear(),purchase.getMonth()+1,close);
    const dueDate = safe(closing.getFullYear(), closing.getMonth() + (due > closing.getDate() ? 0 : 1), due);
    const today = new Date(`${new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})}T12:00:00`); let nextClosing=safe(today.getFullYear(),today.getMonth(),close); if(today>nextClosing) nextClosing=safe(today.getFullYear(),today.getMonth()+1,close);
    const nextDue=safe(nextClosing.getFullYear(),nextClosing.getMonth()+(due>nextClosing.getDate()?0:1),due); const format=(date:Date)=>date.toLocaleDateString('pt-BR');
    return { best: close===31?1:close+1, nextClosing:format(nextClosing), nextDue:format(nextDue), purchaseDue:format(dueDate), risky:purchase.getDate()===close, invalid:close===due };
  },[closingDay,dueDay,simulationDate]);
  return <section id="catalogs" className="page catalogs-page v10-catalogs"><header className="page-header"><div><span>CADASTROS</span><h1>Base configurável do MEG</h1><p>Centralize as opções usadas nos lançamentos sem alterar registros históricos.</p></div><span className="status-pill active">HISTÓRICO PROTEGIDO</span></header>
    <section className="catalog-summary">{[[`Contas financeiras`,`${accounts.filter(x=>x.isActive).length} ativas`,'Monetário e benefício'],['Classificações',`${classifications.length} ativas`,'Aplicadas às despesas'],['Grupos',`${categories.filter(x=>x.isActive&&x.group).length} ativos`,'Despesas e recebimentos'],['Cartões',`${cards.filter(x=>x.isActive).length} ativos`,'Identidade visual automática']].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</section>
    <nav className="catalog-sticky-tabs v10-tabs" role="tablist">{([['accounts','Contas financeiras'],['classifications','Classificações'],['groups','Grupos'],['payments','Formas de pagamento'],['cards','Cartões']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>selectTab(id)}>{label}</button>)}</nav>
    <div className={`v10-catalog-panel ${tab==='cards'?(cardFormOpen?'card-form-open':'card-form-closed'):''}`}>{(tab!=='cards'||cardFormOpen)&&<form className="meg-card v10-catalog-form" onSubmit={submit} noValidate><div className="catalog-form-heading"><div><span className="meg-eyebrow">NOVO CADASTRO</span><h3>{copy[0]}</h3></div>{tab==='cards'&&<button type="button" className="catalog-close-icon" onClick={()=>setCardFormOpen(false)} aria-label="Fechar cadastro de cartão">×</button>}</div><label>Nome *<input ref={firstField} value={name} onChange={e=>setName(e.target.value)} required placeholder={tab==='cards'?'Ex.: LATAM PASS Platinum':tab==='groups'?'Ex.: Atendimentos externos':'Informe o nome'} /></label>
      {tab==='accounts'&&<><label>Escopo financeiro *<select value={detail} onChange={e=>setDetail(e.target.value)} required><option value="">Selecione</option><option>Monetária</option><option>Benefício alimentação</option><option>Benefício refeição</option><option>Benefício transporte</option><option>Outro benefício</option></select></label><label>Tipo *<select value={type} onChange={e=>setType(e.target.value)}><option value="checking">Conta corrente</option><option value="savings">Poupança</option><option value="cash">Dinheiro</option><option value="investment">Investimento</option></select></label><label>Saldo inicial<MEGCurrencyInput value={openingBalance} onValueChange={setOpeningBalance} allowNegative /></label><div className="notice">O saldo inicial gera um evento rastreável. Benefícios permanecem separados do caixa monetário.</div></>}
      {tab==='classifications'&&<><label>Aplicação<input value="Somente despesas" disabled /></label><label>Descrição<textarea value={detail} onChange={e=>setDetail(e.target.value)} maxLength={180}/></label><div className="notice">Receitas usam apenas grupos de recebimento. A classificação é exclusiva para despesas.</div></>}
      {tab==='groups'&&<><label>Tipo *<select value={type} onChange={e=>setType(e.target.value)}><option value="expense">Grupo de despesa</option><option value="income">Grupo de recebimento</option></select></label>{type==='expense'&&<label>Classificação da despesa *<select value={detail} onChange={e=>setDetail(e.target.value)} required><option value="">Selecione</option>{classifications.map(x=><option key={x}>{x}</option>)}</select></label>}<label>Palavras para sugestão automática<input value={extra} onChange={e=>setExtra(e.target.value)} placeholder="Ex.: fisioterapia, paciente" /></label></>}
      {tab==='payments'&&<><label>Natureza *<select value={type} onChange={e=>setType(e.target.value)}><option value="instant">Pagamento imediato</option><option value="credit">Cartão de crédito</option><option value="installment">Crediário</option><option value="benefit">Benefício</option><option value="other">Outro</option></select></label><div className="notice">Crédito e crediário calculam parcelas e vencimentos. O campo Modalidade não é necessário.</div></>}
      {tab==='cards'&&<><label>Emissor<input value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Ex.: Itaú"/></label><label>Bandeira *<select value={extra} onChange={e=>setExtra(e.target.value)} required><option value="">Selecione</option>{brands.map(x=><option key={x}>{x}</option>)}</select></label><div className="launch-form-row"><label>Dia de fechamento *<input type="number" min="1" max="31" value={closingDay} onChange={e=>setClosingDay(e.target.value)}/><small>Dia em que a operadora encerra a fatura.</small></label><label>Dia de vencimento *<input type="number" min="1" max="31" value={dueDay} onChange={e=>setDueDay(e.target.value)}/><small>Dia habitual para pagamento.</small></label></div>{cardDates.invalid&&<div className="notice warn">Fechamento e vencimento não podem ocorrer no mesmo dia.</div>}<section className="card-date-intelligence"><div><span>Melhor dia estimado</span><strong>Dia {cardDates.best}</strong><small>Primeiro dia após o fechamento.</small></div><div><span>Próximo fechamento</span><strong>{cardDates.nextClosing}</strong></div><div><span>Próximo vencimento</span><strong>{cardDates.nextDue}</strong></div><label>Simular uma compra em<input type="date" value={simulationDate} onChange={e=>setSimulationDate(e.target.value)}/></label><div className="invoice-route"><span>Compra em <strong>{new Date(`${simulationDate}T12:00:00`).toLocaleDateString('pt-BR')}</strong></span><b>→</b><span>Vencimento <strong>{cardDates.purchaseDue}</strong></span></div></section>{cardDates.risky&&<div className="notice warn">Compra no dia do fechamento pode cair nesta fatura ou na próxima. Prefira o dia seguinte.</div>}<label>Limite<MEGCurrencyInput value={limit} onValueChange={setLimit}/></label><div className="catalog-card-preview"><strong>{name||'Aguardando descrição'}</strong><span>{detail||'Identidade automática'}</span></div></>}
      {error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={!canWrite||busy||cardDates.invalid}>{busy?'Salvando...':`Salvar ${copy[0].toLowerCase()}`}</button></form>}
      <article className="meg-card v10-catalog-table"><header><div><span className="meg-eyebrow">CADASTRADOS</span><h3>{copy[1]}</h3></div><div className="catalog-table-head-actions"><span className="status-pill active">{rows.length} itens</span>{tab==='cards'&&canWrite&&<button className="catalog-add-icon" onClick={()=>{setCardFormOpen(value=>!value);window.setTimeout(()=>firstField.current?.focus(),200)}} aria-expanded={cardFormOpen} aria-label={cardFormOpen?'Recolher cadastro de cartão':'Cadastrar novo cartão'}>{cardFormOpen?'−':'＋'}</button>}</div></header><div className="table-scroll"><table className="meg-table"><thead><tr><th>{copy[2]}</th><th>{copy[3]}</th><th>{copy[4]}</th><th>Situação</th><th>Ações</th></tr><tr className="table-filter-row"><th><input value={filters.first} onChange={e=>setFilters({...filters,first:e.target.value})} placeholder="Filtrar"/></th><th><input value={filters.second} onChange={e=>setFilters({...filters,second:e.target.value})} placeholder="Filtrar"/></th><th><input value={filters.third} onChange={e=>setFilters({...filters,third:e.target.value})} placeholder="Filtrar"/></th><th><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todas</option><option value="active">Ativa</option><option value="inactive">Inativa</option></select></th><th/></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td><strong>{item.first}</strong></td><td>{item.second}</td><td>{item.third}</td><td><span className={`status-pill ${item.active?'active':''}`}>{item.active?'Ativo':'Inativo'}</span></td><td>{item.active&&canDeactivate&&<button className="secondary-button" onClick={()=>void deactivate(item.id)} disabled={busy}>Inativar</button>}</td></tr>)}</tbody></table>{loading&&<p className="catalog-empty">Carregando dados da base...</p>}{!loading&&!rows.length&&<p className="catalog-empty">Nenhum cadastro corresponde aos filtros.</p>}</div><div className="notice catalog-preservation">Itens vinculados não são excluídos. A inativação impede novos usos e preserva o histórico.</div></article></div>
  </section>;
}
