import { FormEvent, useEffect, useState } from 'react';
import { planningClient, type BudgetStatus } from '../../app/planning-client';
import { readSession } from '../../app/auth-client';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}); const currentMonth=new Date().toISOString().slice(0,7);
export function Planning(){const [month,setMonth]=useState(currentMonth);const [items,setItems]=useState<BudgetStatus[]>([]);const [group,setGroup]=useState('');const [amount,setAmount]=useState('');const [error,setError]=useState('');const canWrite=readSession()?.user.role!=='VIEWER';
async function load(){try{setError('');setItems(await planningClient.list(month))}catch(e){setError(e instanceof Error?e.message:'LOAD_ERROR')}} useEffect(()=>{void load()},[month]);
async function save(e:FormEvent){e.preventDefault();try{await planningClient.save(month,group,Number(amount));setGroup('');setAmount('');await load()}catch(c){setError(c instanceof Error?c.message:'SAVE_ERROR')}}
const total=items.reduce((s,i)=>s+Number(i.amount),0),spent=items.reduce((s,i)=>s+i.spent,0);
return <section className="page planning-page"><header className="page-header"><div><span>Planejamento pessoal</span><h1>Orçamento mensal</h1><p>Defina limites por grupo e acompanhe previsto versus realizado.</p></div><label className="month-control">Mês<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></header>{error&&<div className="auth-error">{error}</div>}
<div className="planning-kpis"><div className="meg-card"><span>Planejado</span><strong>{money.format(total)}</strong></div><div className="meg-card"><span>Realizado</span><strong>{money.format(spent)}</strong></div><div className="meg-card"><span>Disponível</span><strong>{money.format(total-spent)}</strong></div></div>
<div className="planning-layout"><form className="meg-card catalog-form" onSubmit={save}><span className="meg-eyebrow">Novo limite</span><label>Grupo<input value={group} onChange={e=>setGroup(e.target.value)} placeholder="Ex.: Alimentação" required disabled={!canWrite}/></label><label>Valor mensal<input type="number" min=".01" step=".01" value={amount} onChange={e=>setAmount(e.target.value)} required disabled={!canWrite}/></label><button className="auth-submit" disabled={!canWrite}>Salvar orçamento</button></form>
<div className="meg-card budget-list"><span className="meg-eyebrow">Acompanhamento</span>{items.map(item=>{const pct=Math.min(100,item.spent/Number(item.amount)*100);return <article key={item.id}><div><strong>{item.group}</strong><span>{money.format(item.spent)} de {money.format(Number(item.amount))}</span></div><b className={item.remaining<0?'negative':''}>{money.format(item.remaining)}</b><progress value={pct} max="100"/></article>})}{items.length===0&&<p className="catalog-empty">Nenhum orçamento definido para este mês.</p>}</div></div></section>}
